-- This file runs against the default `postgres` database when the container
-- first starts. Build your schema here, then re-run ./setup.sh.
--
-- Typical pattern (see cars-database for a fuller example):
--
-- CREATE DATABASE instagram;
-- \connect instagram
--
-- CREATE TABLE users (
--   id SERIAL PRIMARY KEY,
--   ...
-- );
--
-- INSERT INTO users VALUES (...);
